### ISSUE TITLE
where can i find "ExcelOutputAsset"

### ISSUE THREAD

**Issue by dfmjndm** [rafi1212122/BH3_PS#11]
What is "ExcelOutputAsset" and where can i download it?
Should i download the file and new-build a folder named resources and put the file into the folder？

**Comment by rafi1212122** [comment]
yes you should make folder resources, and put the `ExcelOutputAsset` folder in the resources folder

ExcelOutputAsset is dumped game data, you can try using [this](https://cdn.discordapp.com/attachments/839458853480824835/1101864524132405248/ExcelOutputAsset.zip)

**Comment by dfmjndm** [comment]
the link seems unable to be downloaded from my region.Is there any other plantform such as google drive？and is there any discord channel？

**Comment by rafi1212122** [comment]
try [this](https://crepe.moe/Y2YtVRTf)
