### ISSUE TITLE
Please tell me how to use the web console, or how to get other Valkyries

### ISSUE THREAD

**Issue by onetapv4** [rafi1212122/BH3_PS#17]
Please tell me how to use the web console, or how to get other Valkyries

**Comment by adroitwolf** [comment]
if you already know something about mongodb skills , you can get other chars by this:
1. open resources/ExcelOutputAsset/AvatarData.json,find avatarid who you want to unlock
2. open mongodb/bh3_ps/avatars,add a item like Kiana(avatarId:101),and copy the new item's objectId
3. add this objectid after mongodb/bh3_ps/avatar/(your account )/avatarList

**Comment by adroitwolf** [comment]
![微信图片_20230515151407](https://github.com/rafi1212122/BH3_PS/assets/40268529/549fd124-3199-4b0a-9426-2318c4c393d9)
