### ISSUE TITLE
Need To reinput password

### ISSUE THREAD

**Issue by Liujunhua007** [rafi1212122/BH3_PS#23]
![image](https://github.com/rafi1212122/BH3_PS/assets/62129047/0852e25a-1205-4b1e-aa02-1c43c77797fe)
![image](https://github.com/rafi1212122/BH3_PS/assets/62129047/36d0e8b6-049a-4aaf-8889-be0edf60de2c)

**Comment by rafi1212122** [comment]
does that still happen after restarting the game? if still happen are you using mitmproxy `proxy.py` or some other fiddler script?

**Comment by Liujunhua007** [comment]
using Fiddler Classic which has been setted for grasscuter.&nbsp;
127 0 0 1
443

Q..Q..?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rafi1212122/BH3_PS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 中午1:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rafi1212122/BH3_PS] Need To reinput password (Issue #23)





 
does that still happen after restarting the game? if still happen are you using mitmproxy proxy.py or some other fiddler script?

**Comment by Liujunhua007** [comment]
using Fiddler Classic which has been setted for grasscuter. 
127 0 0 1
443
I see cmd has create account in mogondb table


Q..Q..?
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "rafi1212122/BH3_PS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 中午1:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rafi1212122/BH3_PS] Need To reinput password (Issue #23)





 
does that still happen after restarting the game? if still happen are you using mitmproxy proxy.py or some other fiddler script?

**Comment by Liujunhua007** [comment]
> does that still happen after restarting the game? if still happen are you using mitmproxy `proxy.py` or some other fiddler script?

using Fiddler Classic which has been setted for grasscuter.
127 0 0 1
443
I see cmd has create account in mogondb table

**Comment by rafi1212122** [comment]
```c#
import System;
import System.Windows.Forms;
import Fiddler;
import System.Text.RegularExpressions;

class Handlers
{
    static function OnBeforeRequest(oS: Session)
    {
        if (oS.host.EndsWith(".yuanshen.com") ||
            oS.host.EndsWith(".hoyoverse.com") ||
            oS.host.EndsWith(".mihoyo.com") ||
            oS.host.EndsWith(".yuanshen.com:12401") ||
            oS.host.EndsWith(".starrails.com") ||
            oS.host.EndsWith(".kurogame.com") ||
            oS.host.EndsWith(".zenlesszonezero.com") ||
            oS.host.EndsWith(".api.g3.proletariat.com") ||
            oS.host.EndsWith(".honkaiimpact3.com") ||
            oS.host.EndsWith(".bh3.com") ||
            oS.uriContains("http://overseauspider.yuanshen.com:8888/log"))
        {
            // This can also be replaced with another ip/domain server.
            oS.oRequest.headers.UriScheme = "https";
            // oS.bypassGateway = true;
            oS.host = "127.0.0.1:443";
            // oS["x-overrideHost"] = '2.0.0.100';
        }
    }
};
```
try change the script with that

**Comment by Liujunhua007** [comment]
> ```cs
> import System;
> import System.Windows.Forms;
> import Fiddler;
> import System.Text.RegularExpressions;
> 
> class Handlers
> {
>     static function OnBeforeRequest(oS: Session)
>     {
>         if (oS.host.EndsWith(".yuanshen.com") ||
>             oS.host.EndsWith(".hoyoverse.com") ||
>             oS.host.EndsWith(".mihoyo.com") ||
>             oS.host.EndsWith(".yuanshen.com:12401") ||
>             oS.host.EndsWith(".starrails.com") ||
>             oS.host.EndsWith(".kurogame.com") ||
>             oS.host.EndsWith(".zenlesszonezero.com") ||
>             oS.host.EndsWith(".api.g3.proletariat.com") ||
>             oS.host.EndsWith(".honkaiimpact3.com") ||
>             oS.host.EndsWith(".bh3.com") ||
>             oS.uriContains("http://overseauspider.yuanshen.com:8888/log"))
>         {
>             // This can also be replaced with another ip/domain server.
>             oS.oRequest.headers.UriScheme = "https";
>             // oS.bypassGateway = true;
>             oS.host = "127.0.0.1:443";
>             // oS["x-overrideHost"] = '2.0.0.100';
>         }
>     }
> };
> ```
> 
> try change the script with that

![image](https://github.com/rafi1212122/BH3_PS/assets/62129047/7bf4b4df-683a-4b15-b354-fc34863cbdaa)
![image](https://github.com/rafi1212122/BH3_PS/assets/62129047/03e37f6e-242b-4f45-814f-bbdb19594099)
network fail

**Comment by rafi1212122** [comment]
```c#
import System;
import System.Windows.Forms;
import Fiddler;
import System.Text.RegularExpressions;

class Handlers
{
    static function OnBeforeRequest(oS: Session)
    {
        if (oS.host.EndsWith(".yuanshen.com") ||
            oS.host.EndsWith(".hoyoverse.com") ||
            oS.host.EndsWith(".mihoyo.com") ||
            oS.host.EndsWith(".yuanshen.com:12401") ||
            oS.host.EndsWith(".starrails.com") ||
            oS.host.EndsWith(".kurogame.com") ||
            oS.host.EndsWith(".zenlesszonezero.com") ||
            oS.host.EndsWith(".api.g3.proletariat.com") ||
            oS.host.EndsWith(".honkaiimpact3.com") ||
            oS.host.EndsWith(".bh3.com") &&
            !oS.uriContains("bundle"))
        {
            // This can also be replaced with another ip/domain server.
            oS.oRequest.headers.UriScheme = "https";
            // oS.bypassGateway = true;
            oS.host = "127.0.0.1:443";
            // oS["x-overrideHost"] = '2.0.0.100';
        }
    }
};
```

how about this, i'm sorry if this is not working since i can't test because i don't have cn client

**Comment by Liujunhua007** [comment]
> ```cs
> import System;
> import System.Windows.Forms;
> import Fiddler;
> import System.Text.RegularExpressions;
> 
> class Handlers
> {
>     static function OnBeforeRequest(oS: Session)
>     {
>         if (oS.host.EndsWith(".yuanshen.com") ||
>             oS.host.EndsWith(".hoyoverse.com") ||
>             oS.host.EndsWith(".mihoyo.com") ||
>             oS.host.EndsWith(".yuanshen.com:12401") ||
>             oS.host.EndsWith(".starrails.com") ||
>             oS.host.EndsWith(".kurogame.com") ||
>             oS.host.EndsWith(".zenlesszonezero.com") ||
>             oS.host.EndsWith(".api.g3.proletariat.com") ||
>             oS.host.EndsWith(".honkaiimpact3.com") ||
>             oS.host.EndsWith(".bh3.com") &&
>             !oS.uriContains("bundle"))
>         {
>             // This can also be replaced with another ip/domain server.
>             oS.oRequest.headers.UriScheme = "https";
>             // oS.bypassGateway = true;
>             oS.host = "127.0.0.1:443";
>             // oS["x-overrideHost"] = '2.0.0.100';
>         }
>     }
> };
> ```
> 
> how about this, i'm sorry if this is not working since i can't test because i don't have cn client

still network fail,i try with os cli tomorrow

**Comment by Liujunhua007** [comment]
Finished,finally get into ps,find out that cn cli is 6.7ver which is 0.1 ahead of glb cli(6.6ver)
