### ISSUE TITLE
How to operate after “npm run dev ”? It is the official game to start the game directly

### ISSUE THREAD

**Issue by yehuoshun** [rafi1212122/BH3_PS#4]
How to operate after “npm run dev ”? It is the official game to start the game directly（Google Translation）

**Comment by rafi1212122** [comment]
- install mitmproxy
- run the proxy ```mitmdump -s proxy.py -k```
- launch the game

**Comment by YingXIAmour** [comment]
> * install mitmproxy
> * run the proxy `mitmdump -s proxy.py -k`
> * launch the game

I have done it as required, but I can't login

**Comment by yehuoshun** [comment]
![捕获](https://user-images.githubusercontent.com/69134831/215098216-745c26c6-9e45-46ae-929a-6bbc237860c6.PNG)
It is the official game to start the game directly

**Comment by Kyle873** [comment]
I was having some issues with using mitmproxy as well for some reason, the game just wouldn't redirect properly and I have no idea why as I've used it just fine for other *anime* games before. What I did as a stopgap fix is use Fiddler Classic with this script:

```
import System;
import System.Windows.Forms;
import Fiddler;
import System.Text.RegularExpressions;

class Handlers
{
    static function OnBeforeRequest(oS: Session)
    {
        if (oS.host.EndsWith(".yuanshen.com") ||
            oS.host.EndsWith(".hoyoverse.com") ||
            oS.host.EndsWith(".mihoyo.com") ||
            oS.host.EndsWith(".yuanshen.com:12401") ||
            oS.host.EndsWith(".starrails.com") ||
            oS.host.EndsWith(".kurogame.com") ||
            oS.host.EndsWith(".zenlesszonezero.com") ||
            oS.host.EndsWith(".api.g3.proletariat.com") ||
            oS.host.EndsWith(".honkaiimpact3.com") ||
            oS.host.EndsWith(".bh3.com") ||
            oS.uriContains("http://overseauspider.yuanshen.com:8888/log"))
        {
            // This can also be replaced with another ip/domain server.
            // oS.oRequest.headers.UriScheme = "http";
            // oS.bypassGateway = true;
            oS.host = "localhost";
            // oS["x-overrideHost"] = '2.0.0.100';
        }
    }
};
```
This might come with it's own issues though, as I'm not sure how far we're supposed to be able to get into the login/ship entry process yet.

**Comment by dfmjndm** [comment]
I was having same issues,
![image](https://user-images.githubusercontent.com/57401901/221414475-18a18fa1-a32b-423f-bd88-afa5164ca5e8.png)
![image](https://user-images.githubusercontent.com/57401901/221414494-031cbb3a-7aca-4865-8e28-b92d6007b40e.png)
![image](https://user-images.githubusercontent.com/57401901/221414463-189e4b5f-1234-438b-874f-e3dd88a81480.png)

**Comment by rafi1212122** [comment]
> I was having same issues, ![image](https://user-images.githubusercontent.com/57401901/221414475-18a18fa1-a32b-423f-bd88-afa5164ca5e8.png) ![image](https://user-images.githubusercontent.com/57401901/221414494-031cbb3a-7aca-4865-8e28-b92d6007b40e.png) ![image](https://user-images.githubusercontent.com/57401901/221414463-189e4b5f-1234-438b-874f-e3dd88a81480.png)

<img width="467" alt="image" src="https://user-images.githubusercontent.com/65438157/221414658-6cc8d3e1-bd1b-4713-9a54-887f0c2c3e15.png">

- change your windows proxy settings to mitmproxy and just run the game


<img width="313" alt="image" src="https://user-images.githubusercontent.com/65438157/221414845-dda8f594-55af-4695-9f46-b03f40a5c18e.png">

- when the game connected properly to ps the bottom right corner should be like the pic above



**the ps also only work for sea and global game client without some modification.**

**Comment by dfmjndm** [comment]
Thanks, now it works
