### ISSUE TITLE
How to run the code on remote server

### ISSUE THREAD

**Issue by dfmjndm** [rafi1212122/BH3_PS#6]
I have run the nodejs code on the remote server successfully.What should I do next? I replaced the "127.0.0.1"  in [proxy.py](https://github.com/rafi1212122/BH3_PS/blob/master/proxy.py) with my server's IP address,it doesn't work

**Comment by rafi1212122** [comment]
try to replace ```require('os').hostname()``` in config.ts to remote server ip string
