### ISSUE TITLE
I still can't login

### ISSUE THREAD

**Issue by yehuoshun** [rafi1212122/BH3_PS#8]
![图片](https://user-images.githubusercontent.com/69134831/223327248-be7bd1d4-3114-40cf-b31a-193a40e4f2e7.png)
![图片](https://user-images.githubusercontent.com/69134831/223327429-7406930c-0a6b-4cbd-9ad2-2ad3bc32bb07.png)
![图片](https://user-images.githubusercontent.com/69134831/223327438-a29350ec-3a46-43bb-a492-08c61a94f691.png)
![图片](https://user-images.githubusercontent.com/69134831/223327510-5a7ccaa7-4532-4113-9a55-a9dee703b7d2.png)

**Comment by rafi1212122** [comment]
Hello, it seems that you are using chinese version of the client, it's not currently supported, but you can try to copy bh3_os folder in routes and rename it to bh3_cn

![Screenshot_2023-03-07-13-25-15-12_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/65438157/223328733-81423de7-aad8-4c66-9f87-53f93965f46a.jpg)

**Comment by dfmjndm** [comment]
> ![图片](https://user-images.githubusercontent.com/69134831/223327248-be7bd1d4-3114-40cf-b31a-193a40e4f2e7.png) ![图片](https://user-images.githubusercontent.com/69134831/223327429-7406930c-0a6b-4cbd-9ad2-2ad3bc32bb07.png) ![图片](https://user-images.githubusercontent.com/69134831/223327438-a29350ec-3a46-43bb-a492-08c61a94f691.png) ![图片](https://user-images.githubusercontent.com/69134831/223327510-5a7ccaa7-4532-4113-9a55-a9dee703b7d2.png)


用国际版，官服没用
